### ISSUE TITLE
Idea: reorder the checkbox items

### ISSUE THREAD

**Issue by redlaguna** [staxDB/tasks#10]
Hello!

I installed the module and it works very well. But after placing several items on the checklist, I had the need to reorder them but there is no such option. Maybe in the future you can add the option to sort the items in the checklist. Thank you

**Comment by staxDB** [comment]
With Commit 1496c338b559085492593bc1f3c14526acaf2c8f you are now able to sort items in the task-view.

**Comment by redlaguna** [comment]
Hello, thanks for working on this feature,

I have not been able to perform a satisfactory test.

I have uninstalled the module and when I reinstall it and access the modules in the administration strangely the module is activated. But the tables in the database are not created.

I have reviewed the module_enabled table and the task module is not present but the module is curiously in the list of administration modules as active.

In summary apparently the tables are not created for some reason.

This is the error in the logging:

exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mozmthlb_colons.task' doesn't exist' in /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/db/Command.php:915 Stack trace: #0 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/db/Command.php(915): PDOStatement->execute() #1 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/db/Command.php(362): yii\db\Command->queryInternal('fetchAll', NULL) #2 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/db/Query.php(213): yii\db\Command->queryAll() #3 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(135): yii\db\Query->all(NULL) #4 /home/mozmthlb/public_html/veci.mx/protected/modules/tasks/models/Task.php(227): yii\db\ActiveQuery->all() #5 /home/mozmthlb/public_html/veci.mx/protected/modules/tasks/widgets/MyTasks.php(35): humhub\modules\task\models\Task::findUserTasks(NULL, '5') #6 /home/mozmthlb/public_html/veci.mx/protected/humhub/components/Widget.php(57): humhub\modules\task\widgets\MyTasks->run() #7 /home/mozmthlb/public_html/veci.mx/protected/humhub/widgets/BaseStack.php(85): humhub\components\Widget::widget(Array) #8 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/base/Widget.php(139): humhub\widgets\BaseStack->run() #9 /home/mozmthlb/public_html/veci.mx/protected/humhub/modules/space/views/space/_layout.php(42): yii\base\Widget::widget(Array) #10 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/base/View.php(330): require('/home/mozmthlb/...') #11 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/home/mozmthlb/...', Array) #12 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/base/View.php(152): yii\base\View->renderFile('/home/mozmthlb/...', Array, Object(humhub\modules\space\controllers\SpaceController)) #13 /home/mozmthlb/public_html/veci.mx/protected/humhub/components/Controller.php(124): yii\base\View->render('@humhub/modules...', Array, Object(humhub\modules\space\controllers\SpaceController)) #14 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/base/Controller.php(382): humhub\components\Controller->renderContent('\n<div class="pa...') #15 /home/mozmthlb/public_html/veci.mx/protected/humhub/modules/space/controllers/SpaceController.php(108): yii\base\Controller->render('home', Array) #16 /home/mozmthlb/public_html/veci.mx/protected/humhub/modules/space/controllers/SpaceController.php(90): humhub\modules\space\controllers\SpaceController->actionHome() #17 [internal function]: humhub\modules\space\controllers\SpaceController->actionIndex() #18 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #19 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array) #20 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('', Array) #21 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('space/space', Array) #22 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #23 /home/mozmthlb/public_html/veci.mx/index.php(25): yii\base\Application->run() #24 {main} Next exception 'yii\db\Exception' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mozmthlb_colons.task' doesn't exist The SQL being executed was: SELECT `task`.* FROM `task` LEFT JOIN `content` ON `task`.`id` = `content`.`object_id` LEFT JOIN `contentcontainer` ON `content`.`contentcontainer_id` = `contentcontainer`.`id` LEFT JOIN `user` ON `content`.`created_by` = `user`.`id` LEFT JOIN `task_user` ON task.id=task_user.task_id LEFT JOIN `space_membership` ON contentcontainer.pk=space_membership.space_id AND contentcontainer.class='humhub\\modules\\space\\models\\Space' AND space_membership.user_id=1 LEFT JOIN `space` ON contentcontainer.pk=space.id AND contentcontainer.class='humhub\\modules\\space\\models\\Space' LEFT JOIN `user` `cuser` ON contentcontainer.pk=cuser.id AND contentcontainer.class='humhub\\modules\\user\\models\\User' LEFT JOIN `user_friendship` `cff` ON cuser.id=cff.user_id AND cff.friend_user_id=1 WHERE (`task_user`.`user_id`=1) AND (`task`.`status` != 3) AND (space.id IS NOT NULL AND ( (space_membership.status=3) OR (content.visibility=1 AND space.visibility != 0)) OR cuser.id IS NOT NULL AND ( (content.visibility = 1) OR (content.visibility = 0 AND content.contentcontainer_id=1) OR (content.visibility = 0 AND cff.id IS NOT NULL))OR content.created_by=1) AND (`content`.`object_model`='humhub\\modules\\task\\models\\Task') ORDER BY -task.end_datetime DESC LIMIT 5' in /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/db/Schema.php:636 Stack trace: #0 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/db/Command.php(930): yii\db\Schema->convertException(Object(PDOException), 'SELECT `task`.*...') #1 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/db/Command.php(362): yii\db\Command->queryInternal('fetchAll', NULL) #2 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/db/Query.php(213): yii\db\Command->queryAll() #3 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(135): yii\db\Query->all(NULL) #4 /home/mozmthlb/public_html/veci.mx/protected/modules/tasks/models/Task.php(227): yii\db\ActiveQuery->all() #5 /home/mozmthlb/public_html/veci.mx/protected/modules/tasks/widgets/MyTasks.php(35): humhub\modules\task\models\Task::findUserTasks(NULL, '5') #6 /home/mozmthlb/public_html/veci.mx/protected/humhub/components/Widget.php(57): humhub\modules\task\widgets\MyTasks->run() #7 /home/mozmthlb/public_html/veci.mx/protected/humhub/widgets/BaseStack.php(85): humhub\components\Widget::widget(Array) #8 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/base/Widget.php(139): humhub\widgets\BaseStack->run() #9 /home/mozmthlb/public_html/veci.mx/protected/humhub/modules/space/views/space/_layout.php(42): yii\base\Widget::widget(Array) #10 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/base/View.php(330): require('/home/mozmthlb/...') #11 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/home/mozmthlb/...', Array) #12 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/base/View.php(152): yii\base\View->renderFile('/home/mozmthlb/...', Array, Object(humhub\modules\space\controllers\SpaceController)) #13 /home/mozmthlb/public_html/veci.mx/protected/humhub/components/Controller.php(124): yii\base\View->render('@humhub/modules...', Array, Object(humhub\modules\space\controllers\SpaceController)) #14 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/base/Controller.php(382): humhub\components\Controller->renderContent('\n<div class="pa...') #15 /home/mozmthlb/public_html/veci.mx/protected/humhub/modules/space/controllers/SpaceController.php(108): yii\base\Controller->render('home', Array) #16 /home/mozmthlb/public_html/veci.mx/protected/humhub/modules/space/controllers/SpaceController.php(90): humhub\modules\space\controllers\SpaceController->actionHome() #17 [internal function]: humhub\modules\space\controllers\SpaceController->actionIndex() #18 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #19 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array) #20 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('', Array) #21 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('space/space', Array) #22 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #23 /home/mozmthlb/public_html/veci.mx/index.php(25): yii\base\Application->run() #24 {main} Additional Information: Array ( [0] => 42S02 [1] => 1146 [2] => Table 'mozmthlb_colons.task' doesn't exist )

**Comment by staxDB** [comment]
I'm sorry about that, but this doesn't seem to be an issue with my module. For whatever reason, your migration has not been executed. First of all, take a look at `administration -> information -> migration`. Maybe here are the migrations listed, that have not been executed!

Then try something like that:

```php
php yii migrate/up --migrationPath='@app/modules/task/migrations'
```

You can find the docs [here](http://docs.humhub.org/dev-dev-db.html).

Another option would be to remove the task-folder in your modules directory and then reinstall the latest task-module version via git `git clone https://github.com/staxDB/tasks.git task` or alternatively download the module manually and install it in your `protected/modules` folder

If that doesn't help, please ask in the community!

**Comment by redlaguna** [comment]
Hello,

Thank you very much for the help, it works correctly. Although I think it would be more practical for the reordering to be done in the edition, but it works perfect as well.
