### ISSUE TITLE
Error on loading Dashboard if dashboard url is not http://site/dashboard/

### ISSUE THREAD

**Issue by bumrufus** [staxDB/tasks#3]
My Site is in german and the main site is http://intranet/uebersicht instead of http://intranet/dashboard
If i create a task the dashboard isn't loading anymore Error:

`{
    "url": "/dashboard/dashboard/stream?mode=normal",
    "status": 500,
    "response": {
        "name": "Internal Server Error",
        "message": "Es ist ein interner Serverfehler aufgetreten.",
        "code": 0,
        "status": 500
    },
    "textStatus": "error",
    "dataType": "json",
    "xhr": {
        "readyState": 4,
        "responseText": "{\"name\":\"Internal Server Error\",\"message\":\"Es ist ein interner Serverfehler aufgetreten.\",\"code\":0,\"status\":500}",
        "responseJSON": {
            "name": "Internal Server Error",
            "message": "Es ist ein interner Serverfehler aufgetreten.",
            "code": 0,
            "status": 500
        },
        "status": 500,
        "statusText": "Internal Server Error"
    },
    "name": "Internal Server Error",
    "message": "Es ist ein interner Serverfehler aufgetreten.",
    "code": 0,
    "error": {},
    "errorThrown": "Internal Server Error",
    "validationError": false
}`

**Comment by staxDB** [comment]
Should be fixed in 8c3c262dd391876a61d8a7431ed618c709fb2e68
