### ISSUE TITLE
Calendar Entry

### ISSUE THREAD

**Issue by bumrufus** [staxDB/tasks#5]
deadline is 31.12.2019 but in the calendar it shows an entry every day of december 2019 
![1](https://user-images.githubusercontent.com/34074733/36140522-d7409304-10a1-11e8-92a7-7efc082a130c.PNG)
![2](https://user-images.githubusercontent.com/34074733/36140523-d760e672-10a1-11e8-9fc3-7580c983ecb2.PNG)

**Comment by staxDB** [comment]
Fixed in 8528ec3f0e8019a4f7eddcb0ed3d162d4bf0825a.
Now only the Deadline will appear in the calendar!
